#!/bin/sh

workspace=server

# only get files from this workspace
server_staged_changes_full_path=$(git diff --name-only --cached | xargs git ls-files --cached | grep "^$workspace/")
# remove workspace prefix
server_staged_changes=$(echo "$server_staged_changes_full_path" | sed "s/^$workspace\///")

ts_js_staged_changes_full_path=$(echo "$server_staged_changes_full_path" | grep -E "\.(js|ts)$")
ts_js_staged_changes=$(echo "$server_staged_changes" | grep -E "\.(js|ts)$")

if ! [ -z $ts_js_staged_changes ]; then
  printf "\nℹ️ Type checking workspace\n⚠️ This includes unstaged changes\n\n" && \
  # Tip: create a workspace script `"lint:types": "tsc --noEmit"` to type check with your project settings
  npm run lint:types -w=$workspace && \
  printf "\nℹ️ Linting staged files in workspace" && \
  npm run lint -w=$workspace -- --fix $ts_js_staged_changes
  # check the exit code
  if [ $? -ne 0 ]; then
    exit 1
  fi
  echo "$ts_js_staged_changes_full_path" | xargs git add
else
  printf "\n⛷️ No staged changes to TypeScript or JavaScript: Skipping type checking and linting\n"
fi

prettier_staged_changes_full_path=$(echo "$server_staged_changes_full_path" | grep -E "\.(js|ts|json)$")
if [ -n "$prettier_staged_changes_full_path" ]; then
  printf "\nℹ️ Formatting staged TypeScript and JavaScript in workspace\n" && \
  echo "$prettier_staged_changes_full_path" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
  echo "$prettier_staged_changes_full_path" | xargs git add
else
  printf "\n⛷️ No staged changes to TypeScript or JavaScript: Skipping formatting\n\n"
fi

exit 0
